insert into subjects (id, name, description, `semester`, hours_in_semester, ects, field_id) VALUES(1, 'COMPUTER SCIENCE', 'Learning Java and Spring', 'FIRST', 45, 15, 24);
insert into subjects (id, name, description, `semester`, hours_in_semester, ects, field_id) VALUES(2, 'COMPUTER SCIENCE', 'Learning Java and Spring', 'FIRST', 45, 15, 25);
insert into subjects (id, name, description, `semester`, hours_in_semester, ects, field_id) VALUES(3, 'COMPUTER SCIENCE', 'Learning Java and Spring', 'FIRST', 45, 15, 28);
insert into subjects (id, name, description, `semester`, hours_in_semester, ects, field_id) VALUES(4, 'COMPUTER SCIENCE', 'Learning Java and Spring', 'FIRST', 45, 15, 29);
insert into subjects (id, name, description, `semester`, hours_in_semester, ects, field_id) VALUES(5, 'COMPUTER SCIENCE', 'Learning Java and Spring', 'FIRST', 45, 15, 1);
insert into subjects (id, name, description, `semester`, hours_in_semester, ects, field_id) VALUES(6, 'SYSTEMY INŻYNIERII WIEDZY', 'Learning Java and Spring', 'SECOND', 15, 5, 24);
insert into subjects (id, name, description, `semester`, hours_in_semester, ects, field_id) VALUES(7, 'SYSTEMY INŻYNIERII WIEDZY', 'Learning Java and Spring', 'SECOND', 15, 5, 25);
insert into subjects (id, name, description, `semester`, hours_in_semester, ects, field_id) VALUES(8, 'SYSTEMY INŻYNIERII WIEDZY', 'Learning Java and Spring', 'SECOND', 15, 5, 28);
insert into subjects (id, name, description, `semester`, hours_in_semester, ects, field_id) VALUES(9, 'SYSTEMY INŻYNIERII WIEDZY', 'Learning Java and Spring', 'SECOND', 15, 5, 29);
insert into subjects (id, name, description, `semester`, hours_in_semester, ects, field_id) VALUES(10, 'SYSTEMY INŻYNIERII WIEDZY', 'Learning Java and Spring', 'SECOND', 15, 5, 1);
insert into subjects (id, name, description, `semester`, hours_in_semester, ects, field_id) VALUES(11, 'SYSTEMY STEROWANIA I WSPOMAGANIA DECYZJI', 'Learning Java and Spring', 'THIRD', 15, 5, 24);
insert into subjects (id, name, description, `semester`, hours_in_semester, ects, field_id) VALUES(12, 'SYSTEMY STEROWANIA I WSPOMAGANIA DECYZJI', 'Learning Java and Spring', 'THIRD', 15, 5, 25);
insert into subjects (id, name, description, `semester`, hours_in_semester, ects, field_id) VALUES(13, 'SYSTEMY STEROWANIA I WSPOMAGANIA DECYZJI', 'Learning Java and Spring', 'THIRD', 15, 5, 28);
insert into subjects (id, name, description, `semester`, hours_in_semester, ects, field_id) VALUES(14, 'SYSTEMY STEROWANIA I WSPOMAGANIA DECYZJI', 'Learning Java and Spring', 'THIRD', 15, 5, 29);
insert into subjects (id, name, description, `semester`, hours_in_semester, ects, field_id) VALUES(15, 'SYSTEMY STEROWANIA I WSPOMAGANIA DECYZJI', 'Learning Java and Spring', 'THIRD', 15, 5, 1);
insert into subjects (id, name, description, `semester`, hours_in_semester, ects, field_id) VALUES(16, 'Technika wysokich napięć', 'Learning Java and Spring', 'FOURTH', 60, 30, 1);
insert into subjects (id, name, description, `semester`, hours_in_semester, ects, field_id) VALUES(17, 'Technika wysokich napięć', 'Learning Java and Spring', 'FIRST', 60, 30, 12);
insert into subjects (id, name, description, `semester`, hours_in_semester, ects, field_id) VALUES(18, 'Technika wysokich napięć', 'Learning Java and Spring', 'FOURTH', 60, 30, 22);
insert into subjects (id, name, description, `semester`, hours_in_semester, ects, field_id) VALUES(19, 'Technika wysokich napięć', 'Learning Java and Spring', 'FOURTH', 60, 30, 9);
insert into subjects (id, name, description, `semester`, hours_in_semester, ects, field_id) VALUES(20, 'Technika wysokich napięć', 'Learning Java and Spring', 'FOURTH', 60, 30, 23);
insert into subjects (id, name, description, `semester`, hours_in_semester, ects, field_id) VALUES(21, 'Mechanika', 'Learning Java and Spring', 'FIFTH', 30, 20, 1);
insert into subjects (id, name, description, `semester`, hours_in_semester, ects, field_id) VALUES(22, 'Mechanika', 'Learning Java and Spring', 'SECOND', 30, 20, 12);
insert into subjects (id, name, description, `semester`, hours_in_semester, ects, field_id) VALUES(23, 'Mechanika', 'Learning Java and Spring', 'FIFTH', 30, 20, 2);
insert into subjects (id, name, description, `semester`, hours_in_semester, ects, field_id) VALUES(24, 'Mechanika', 'Learning Java and Spring', 'FIFTH', 30, 20, 4);
insert into subjects (id, name, description, `semester`, hours_in_semester, ects, field_id) VALUES(25, 'Mechanika', 'Learning Java and Spring', 'FIFTH', 30, 20, 5);
insert into subjects (id, name, description, `semester`, hours_in_semester, ects, field_id) VALUES(26, 'Inżynieria materiałowa', 'Learning Java and Spring', 'SIXTH', 15, 5, 1);
insert into subjects (id, name, description, `semester`, hours_in_semester, ects, field_id) VALUES(27, 'Inżynieria materiałowa', 'Learning Java and Spring', 'SIXTH', 15, 5, 2);
insert into subjects (id, name, description, `semester`, hours_in_semester, ects, field_id) VALUES(28, 'Inżynieria materiałowa', 'Learning Java and Spring', 'SIXTH', 15, 5, 3);
insert into subjects (id, name, description, `semester`, hours_in_semester, ects, field_id) VALUES(29, 'Inżynieria materiałowa', 'Learning Java and Spring', 'SIXTH', 15, 5, 4);
insert into subjects (id, name, description, `semester`, hours_in_semester, ects, field_id) VALUES(30, 'Inżynieria materiałowa', 'Learning Java and Spring', 'SIXTH', 15, 5, 5);
insert into subjects (id, name, description, `semester`, hours_in_semester, ects, field_id) VALUES(31, 'Podstawy programowania', 'Learning Java and Spring', 'SEVENTH', 45, 25, 1);
insert into subjects (id, name, description, `semester`, hours_in_semester, ects, field_id) VALUES(32, 'Podstawy programowania', 'Learning Java and Spring', 'SEVENTH', 45, 25, 24);
insert into subjects (id, name, description, `semester`, hours_in_semester, ects, field_id) VALUES(33, 'Podstawy programowania', 'Learning Java and Spring', 'SEVENTH', 45, 25, 25);
insert into subjects (id, name, description, `semester`, hours_in_semester, ects, field_id) VALUES(34, 'Podstawy programowania', 'Learning Java and Spring', 'SEVENTH', 45, 25, 23);
insert into subjects (id, name, description, `semester`, hours_in_semester, ects, field_id) VALUES(35, 'Podstawy programowania', 'Learning Java and Spring', 'SEVENTH', 45, 25, 22);
