insert into teachers (id, first_name, last_name, email, age, user_details_id) values (1, 'Grzegorz', 'Wrzyszcz', 'g.wrzyszcz@gmail.com', 48, 3);
insert into teachers (id, first_name, last_name, email, age) values (2, 'Jagoda', 'Wosz', 'j.wosz@gmail.com', 33);
insert into teachers (id, first_name, last_name, email, age) values (3, 'Adam', 'Wojtyna', 'a.wojtyna@gmail.com', 40);
insert into teachers (id, first_name, last_name, email, age) values (4, 'Jarosław', 'Widera', 'j.widera@gmail.com', 55);
insert into teachers (id, first_name, last_name, email, age, user_details_id) values (5, 'Ludwik', 'Kostro', 'l.kostro@gmail.com', 48, 2);
insert into teachers (id, first_name, last_name, email, age) values (6, 'Marian', 'Kowalska', 'm.kowalska@gmail.com', 33);
insert into teachers (id, first_name, last_name, email, age) values (7, 'Maximilian', 'Batista', 'm.batista@gmail.com', 40);
insert into teachers (id, first_name, last_name, email, age) values (8, 'Nikolas', 'Adamczuk', 'n.adamczuk@gmail.com', 55);
insert into teachers (id, first_name, last_name, email, age) values (9, 'Orest', 'Szafarczyk', 'o.szafarczyk@gmail.com', 48);
insert into teachers (id, first_name, last_name, email, age) values (10, 'Oskar', 'Trzaskoma', 'o.trzaskoma@gmail.com', 33);
insert into teachers (id, first_name, last_name, email, age) values (11, 'Petroniusz', 'Tarczewski', 'p.tarczewski@gmail.com', 40);
insert into teachers (id, first_name, last_name, email, age) values (12, 'Remigiusz', 'Śliwa', 'r.śliwa@gmail.com', 55);
